name: PR Builder

on:
  pull_request:
    branches: [ develop, main, chore/*, feat/*, test/*, fix/*, refactor/* ]

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: debug unit test
        run: ./gradlew testDebugUnitTest